[package]
name = "anchor-lints-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
clippy_utils.workspace = true
once_cell = "1.21.3"